#!/bin/bash
sam
total 24
-rw-r--r-- 1 root root  16 Mar  2 04:19 0-current_working_directory
-rwxr--r-- 1 root root  24 Mar  2 04:30 1-listit
-rw-r--r-- 1 root root  18 Mar  2 05:18 2-bring_me_home
-rw-r--r-- 1 root root  16 Mar  2 04:54 3-listfiles
-rw-r--r-- 1 root root  17 Mar  2 04:56 4-listmorefiles
-rw-r--r-- 1 root root   0 Mar  2 05:14 5-listfilesdigitonly
-rw-r--r-- 1 root root 334 Mar  2 05:10 README.md
